---
- hosts: all
  tasks:
  - name: Get whoami information
    ansible.windows.win_whoami:
  
  - name: Run basic PowerShell script
    ansible.windows.win_powershell:
      script: |
        echo "Hello World"

  - name: Get info for all installed services
    ansible.windows.win_service_info:
    register: service_info
