---
- hosts: all
  tasks:
  - name: Get whoami information
    ansible.windows.win_whoami:
  
  - name: Run basic PowerShell script
    ansible.windows.win_powershell:
      script: |
        echo "Hello World"
