---
- hosts:
    - all
  tasks:
    - name: Install windows collection
      ansible.builtin.command: ansible-galaxy collection install ansible.windows


- hosts: all
  tasks:
  - name: Get whoami information
    ansible.windows.win_whoami:
  
  - name: Run basic PowerShell script
    ansible.windows.win_powershell:
      script: |
        echo "Hello World"
