---
- hosts: all
  become: yes

  tasks:
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql

    - name: "Execute script from command"
      command: "psql {{ db_name }} -c 'SELECT * FROM example'"
      become_user: postgres
      register: sql_response_variable
  