---
- hosts: all
  become: yes

  tasks:
    - name: Populate service facts
      service_facts:

    - name:
      debug:
        msg: Postgresql installed!
        when: "'postgresql.service' in services"

    - name: "Execute script from command"
      command: "psql {{ db_name }} -c 'SELECT * FROM example'"
      become_user: postgres
      register: sql_response_variable

    - name: "Print output"
      debug:
        var: sql_response_variable.stdout_lines
  