- hosts:
    - all
  tasks:
    - name: Display hostnames natively
      ansible.builtin.debug:
        msg: 
          - "Inventory Name: {{ inventory_hostname }}"
          - "Actual System Hostname: {{ ansible_facts.hostname }}"
          - "System FQDN: {{ ansible_facts.fqdn }}"