---
- hosts: localhost
  connection: local
  pre-tasks:
    - name: Install postgreSQL collection
      ansible.builtin.command: ansible-galaxy collection install community.postgresql

- name: install-database 
  import_playbook: install-database.yml
  
