---
- hosts: databases
  become: yes
  collections:
    - microsoft.sql
  vars:
    mssql_accept_microsoft_odbc_driver_for_sql_server_eula: true
    mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
    mssql_accept_microsoft_sql_server_standard_eula: true
    mssql_version: 2022
    mssql_password: "p@55w0rD"
    mssql_edition: Developer
    mssql_run_selinux_confined: true
    mssql_manage_selinux: true
  roles:
    - microsoft.sql.server
