---
- hosts:
    - all
  tasks:
    - name: Install servicenow collection
      ansible.builtin.command: ansible-galaxy collection install servicenow.itsm

- hosts:
    - all
  tasks:
    - name: Create change request
      servicenow.itsm.change_request:
        instance:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"

        type: standard
        state: new
        requested_by: System Administrator
        short_description: Install new Cisco
        description: Please install new Cat. 6500 in Data center 01
        priority: moderate
        risk: low
        impact: low

        other:
          expected_start: 2021-02-12
    - name: Retrieve all incidents
      servicenow.itsm.incident_info:
        instance:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
      register: result  
  