---
- hosts:
    - all
  tasks:
    - name: Install servicenow collection
      ansible.builtin.command: ansible-galaxy collection install servicenow.itsm

collections:
  - name: servicenow.itsm
- hosts:
    - all
  tasks:
    - name: Retrieve all incidents
      servicenow.itsm.incident_info:
      register: result  
  