- name: Listen for newly added ConfigMap resources
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: ConfigMap
        namespace: default
  rules:
    - name: Notify
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: NtfyTemplate
          organization: Default
          job_args:
            extra_vars:
              message: from eda
              sleep: 1  